### ISSUE TITLE
Item not found on Google Play

### ISSUE THREAD

**Issue by TonyTangAndroid** [jrvansuita/MaterialAbout#1]
Hello there, just a quick note that the app seems to be not available in Google Play.

**Comment by Mauker1** [comment]
+1 Couldn't find it either.

**Comment by jrvansuita** [comment]
https://play.google.com/store/apps/details?id=com.vansuita.materialabout.sample


Sorry, will fix it

**Comment by jrvansuita** [comment]
Readme.md Fixed
