### ISSUE TITLE
Giving me this error

### ISSUE THREAD

**Issue by Abhishekbhat1996** [jrvansuita/MaterialAbout#16]
java.lang.NoSuchFieldError: com.vansuita.materialabout.R$id.card_holder

**Comment by jrvansuita** [comment]
What's the version you are using?

**Comment by Abhishekbhat1996** [comment]
v0.0.7

**Comment by jrvansuita** [comment]
Try 0.0.9

**Comment by Abhishekbhat1996** [comment]
Ok..Thanks fr replying

**Comment by Abhishekbhat1996** [comment]
Got it the problem was your about.xml was overriding with that of mine. Thank you great library by the way.

**Comment by jrvansuita** [comment]
Nice, I changed all layout names in case of too used names.
