### ISSUE TITLE
Skype Click not working 

### ISSUE THREAD

**Issue by Shajeel-Afzal** [jrvansuita/MaterialAbout#22]
I have added my skype username using the function `.addSkypeLink("MY_SKYPE_USERNAME")` but the click on the skype button is not working. I have also trying to enter my phone number but no success. Please let me know what should I enter as skype username.

**Comment by jrvansuita** [comment]
Use like this `.addSkypeLink("phoneNumber")`. Make sure you have skype app installed on your device. Otherwise nothing will happen. I will document with java doc every method.

**Comment by jrvansuita** [comment]
This happen when I click on that button from material about.

![screenshot_20170223-225029](https://cloud.githubusercontent.com/assets/12175215/23287244/f04fee38-fa1a-11e6-9135-b5fe9f668866.png)

**Comment by Shajeel-Afzal** [comment]
Thanks for letting me know. You can show the error message instead if Skype is not installed. It will help the user to understand why nothing is happening!

**Comment by jrvansuita** [comment]
Yeah, or maybe it will be nice to show the skype website. Show some profile, I don't know if it's possible. Can you help me out?
