### ISSUE TITLE
Youtube Channel Link not working

### ISSUE THREAD

**Issue by Shajeel-Afzal** [jrvansuita/MaterialAbout#23]
I am trying to add the Youtube Channel using the Channel ID but it is not working. My channel ID is "UCyiIAz-Tv3SxLMml93g3tMg", When I am trying to open the channel via the about screen it is saying that the channel does not exists. How are you finding the channel ID?

**Comment by jrvansuita** [comment]
Try like this `.addYoutubeChannelLink("CaseyNeistat")`.
It is the channel name.
