### ISSUE TITLE
Unable to import into Gardle

### ISSUE THREAD

**Issue by AizazAZ** [jrvansuita/MaterialAbout#24]
Unable to integrate with latest build tools '+' in gradle is not acceptable :(

**Comment by jrvansuita** [comment]
Possibly you forgot this below repository:

```
allprojects {
    repositories {
    ...
    maven { url "https://jitpack.io" }
    }
}
```

If it's not working with the plus (+) you should specify the version.
Like: `compile 'com.github.jrvansuita:MaterialAbout:0.1.0'`
