### ISSUE TITLE
Set/Remove padding, shadow etc

### ISSUE THREAD

**Issue by Bennith** [jrvansuita/MaterialAbout#26]
Hi @jrvansuita nice librarie.

I wish to see implemented the ability to remove padding from the view.
Cant see where this being set in my app.
Does the about view always stretch full width? 
Does padding get added by default?

if not, would like to see something like the below;

AboutBuilder.with(activity)
    .setPadding(-10)//padding
    .setElevation(1) //shadow
    .setMargin(-1) //margin
    ...
    ...
    build();

**Comment by jrvansuita** [comment]
Thanks my friend. Feel free to help me with this. Try me a pull request, or give me some time to do it.

**Comment by Bennith** [comment]
Thanks for quick response. Will see how I go.
So it does get padding added by default?

**Comment by jrvansuita** [comment]
Yes, It should be set by the Builder, but it's not. Today, I have it fixed in the layout xml. We need to bring this configurations to java, and set it programmatically.

**Comment by Bennith** [comment]
> Yes, It should be set by the Builder, but it's not. Today, I have it fixed in the layout xml. We need to bring this configurations to java, and set it programmatically.

Yes is see this for other .set() - like divider line height etc values done in the java files, which in turn edit the layout xmls as such yeah.

**Comment by jrvansuita** [comment]
ok, will be done for the next couple days. If you are rushed, you can create a pull request.

**Comment by Bennith** [comment]
no, thats ok, just like to see features added to the library which may make this awesome lib even better.

**Comment by Bennith** [comment]
Was able to remove Margin on the CardView inside the build(); using below

public void onCreate(Bundle savedInstanceState) {
        //...
        //...
        CardView layout = (CardView)findViewById(R.id.card_holder);
        CardView.LayoutParams params = new CardView.LayoutParams(CardView.LayoutParams.MATCH_PARENT, CardView.LayoutParams.WRAP_CONTENT);
        params.setMargins(0,0,0,0);
        layout.setLayoutParams(params);
        //...
        //..
}

**Comment by jrvansuita** [comment]
https://github.com/jrvansuita/MaterialAbout/releases/tag/0.1.2
