### ISSUE TITLE
.. Fragment Tabs inside About Layout

### ISSUE THREAD

**Issue by Bennith** [jrvansuita/MaterialAbout#29]
Yep, Im say it ... @jrvansuita 

.. Add Fragment Tabs inside About Layout View, yep thats right I said it.
Something special like ...
AboutBuilder.with(activity)
.addFragment(new MyFragmentTabHome(), _SharedPrefsUserName)
.addFragment(new MyFragmentTabApps(), "My Apps")
.addFragment(new MyFragmentTabWebViewFacebook(), "My Facebook")
...
...
...
//this is cray,
.build();

Can be done other ways I know.. but still this would be epic.

**Comment by jrvansuita** [comment]
Can you demonstrate for me how it could be visual? Do you have any image to show how epic it could be?

**Comment by Bennith** [comment]
Please see http://imgur.com/a/L4gqN

**Comment by jrvansuita** [comment]
Great job! I will try it. Will let you know.

**Comment by Bennith** [comment]
Was able to achieve without hacking the lib.
http://imgur.com/a/cfFMl

**Comment by jrvansuita** [comment]
Hey man, can ou help me with a pull request of your working code? Would be nice check it out.

**Comment by Bennith** [comment]
Not much to it just wrapped the view xml in linear layout (match_parent) with the tabs below it. Then just set the padding, max height etc of the about xml element to match and fixed.

**Comment by jrvansuita** [comment]
Yeap! Sorry man, I'm to busy right now. I can't handle this because I'm out off time. Can you implement that feature and create a pull request for me?  I will be really thankfull.

@Bennith

**Comment by jrvansuita** [comment]
Ok, Closing these. No one interested on developing this func.
