### ISSUE TITLE
Privacy policy link

### ISSUE THREAD

**Issue by marbat87** [jrvansuita/MaterialAbout#35]
As the title tolds, it would be very useful having a "pivacy policy" link

Regards,
Marcello

**Comment by jrvansuita** [comment]
Why do you want a privacy policy? It's an open source with a MIT license.

**Comment by marbat87** [comment]
Because it is now mandatory for application which request some kind of permissions (phone related permissions for example).

Regards

**Comment by jrvansuita** [comment]
Ok, https://www.docracy.com/2d0kis6uc2.

**Comment by marbat87** [comment]
@jrvansuita  I'm sorry but you misunderstood me :)
I meant that would be useful a new function like `addPrivacyPolicyLink(String url)`

So each one can put there the link with its own privacy policy ;)
The function will just add the icon and open the link onClick.

Regards

**Comment by jrvansuita** [comment]
Ohhh, okay, now I got you. Can you  create a pull request?

**Comment by marbat87** [comment]
Sure.
Any suggestion about the icon?

**Comment by marbat87** [comment]
@jrvansuita Done with #36  :)

Regards
