### ISSUE TITLE
Used Libraries

### ISSUE THREAD

**Issue by Devofure** [jrvansuita/MaterialAbout#38]
Hi, could you add "Used Libraries"?

**Comment by jrvansuita** [comment]
Readme updated.

    ```
compile "com.android.support:appcompat-v7:$supportLibVersion"
    compile "com.android.support:cardview-v7:$supportLibVersion"
    compile 'com.github.jrvansuita:IconHandler:+'
```

**Comment by Devofure** [comment]
Hi, very sorry for the misunderstanding, I was asking for an action item, "Used Libraries" in the about View.

**Comment by iRYO400** [comment]
Upvote! It would be usefull

**Comment by kumar-aakash86** [comment]
I waslooking for the same action in this library.
