### ISSUE TITLE
"IconHandler:+" Dynamic version 

### ISSUE THREAD

**Issue by ykAR6Bqy5DeG** [jrvansuita/MaterialAbout#39]
In the library's build.gradle, current version is using dynamic version
`compile 'com.github.jrvansuita:IconHandler:+'`
It may cause weird bugs when IconHandler is updated. 
Additionally, it requires checking newest version and increases build time every time Android Studio starts. This is really inconvenient when developer is editing project during offline.
Using a stable version of IconHandler will work :)

**Comment by jrvansuita** [comment]
That's why you have "(See latest release)" just above `compile 'com.github.jrvansuita:IconHandler:+'`

**Comment by ykAR6Bqy5DeG** [comment]
I looked the newest version 0.1.4. Even if I use latest release 0.1.4, IconHandler is still using a dynamic version(IconHandler:+').
