### ISSUE TITLE
Maybe the URLs should be marked as translatable="false"

### ISSUE THREAD

**Issue by ordago** [jrvansuita/MaterialAbout#4]
<string name="url_twitter_website">https://twitter.com/%s</string>

to

<string name="url_twitter_website" translatable="false">https://twitter.com/%s</string>

**Comment by jrvansuita** [comment]
No, I did some changes in your pull request. There's no need to duplicate equal content to another string xml. And I also created a new strings xml called consts.xml. It keeps all the constantes(URLS). Check it up.

**Comment by ordago** [comment]
won't Lint complain if those strings in consts.xml are not translated?

**Comment by jrvansuita** [comment]
No, consts.xml got this declaration:
```xml
<resources
    xmlns:tools="http://schemas.android.com/tools"
    tools:ignore="MissingTranslation">
    <!-- .......  -->
</resources>
```
