### ISSUE TITLE
Can't customize the AboutBuilder because it's final

### ISSUE THREAD

**Issue by nandorrb** [jrvansuita/MaterialAbout#42]
Hi friend,
I've got some issues with youtube channel link, I want to put this link:

https://www.youtube.com/channel/UC2axCb0v1ZToELjfifeUpJA

on my AboutBuilder:

```java
 .addYoutubeChannelLink("UC2axCb0v1ZToELjfifeUpJA")
````
However it throws me this:

https://www.youtube.com/user/UC2axCb0v1ZToELjfifeUpJA

So I wanted to customize the ***AboutBuilder.class*** , by extending that class, however it's imposible because it's a final class: 
```java
public final class AboutBuilder {
    private Context context;
    private IntentUtil util;
    private String name;
    private String subTitle;
    private String brief;
    private String appName;
    private String appTitle;
    private Bitmap photo;
    private Bitmap cover;
    private Bitmap appIcon;
    private int nameColor;
    private int subTitleColor;
    private int briefColor;
    private int iconColor;
    private int backgroundColor;
    private boolean showDivider = true;
    private int dividerColor = 0;
    private int dividerHeight = 4;
    private int dividerDashWidth = 15;
    private int dividerDashGap = 15;
    private boolean linksAnimated = true;
    private int linksColumnsCount = 5;
    private int actionsColumnsCount = 2;
    private boolean wrapScrollView = false;
    private boolean showAsCard = true;
    private LinkedList<Item> links = new LinkedList();
    private LinkedList<Item> actions = new LinkedList();

    AboutBuilder(Context context) {
...
```

So I copied ***AboutBuilder.class***  as  ***PrimalAboutBuilder.class*** and ***AboutView.class***  as  a***PrimalAboutView.class***, then extending them without success, due to ***can't cast CustomAboutBuilder as AboutBuilder*** error.

This is my ***CustomAboutBuilder.class*** : 

```java
public class CustomAboutBuilder extends PrimalAboutBuilder {

    private Context context;
    private IntentUtil util;
    private String name;
    private String subTitle;
    private String brief;
    private String appName;
    private String appTitle;
    private Bitmap photo;
    private Bitmap cover;

    CustomAboutBuilder(Context context) {
        super(context);
        this.context = context;
        this.util = new IntentUtil(context);
    }

    @Override
    public int getLastActionId() {
        return super.getLastActionId();
    }

    @Override
    public Item getLastAction() {
        return super.getLastAction();
    }

    @Override
    public int getLastLinkId() {
        return super.getLastLinkId();
    }

    @Override
    public Item getLastLink() {
        return super.getLastLink();
    }
.
.
.
.
}
```
My questions are:
* How can I fix this youtube channel problem?
* Why are those classes, ***AboutBuilder***, ***AboutView***  ***final*** ?
* How can this library be more customizable?

Thank you for your time.

**Comment by jrvansuita** [comment]
Ok, I fixed the issue for you. Now you have the 1.6 release, where you can find both: `addYoutubeChannelLink()` and `addYoutubeUserLink()`. It's my wish to keep the library fresh and easy to use. I want more and more people use the lib, so I turned it to final and always available to everyone to help me with pull requests.
