### ISSUE TITLE
Quando vou sincronizar no gradle da esse erro ai, sabe me dizer pq?

### ISSUE THREAD

**Issue by mauricioedu** [jrvansuita/MaterialAbout#43]
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by jrvansuita** [comment]
Check your AS config and Android SDK. This error is not related with this library.

**Comment by mauricioedu** [comment]
o erro vem pq não compila na versão compileSdkVersion 23

**Comment by jrvansuita** [comment]
Testa com a seguinte config:

```xml

ext {
    compileSdkVersion = 25
    buildToolsVersion = '25.0.3'
    targetSdkVersion = compileSdkVersion

    supportLibVersion = '25.3.1'
}
```


O Sample project está usando essa config.

**Comment by mauricioedu** [comment]
Valeu, mas já deu certo aqui só esqueci de mandar que tinha conseguido kkk
