### ISSUE TITLE
using of .addDonateAction((Intent))null)

### ISSUE THREAD

**Issue by aaravchaudhary** [jrvansuita/MaterialAbout#47]
how can i use .addDonateAction and all other such actions eg changelogAction ,RemoveAdActioin.I am new to this feature so i need help..

**Comment by jrvansuita** [comment]
Look here: https://developer.android.com/reference/android/content/Intent.html

**Comment by aaravchaudhary** [comment]
Plsss..explain further cannot get the exact solution..stucked in it from
last 7 days..

**Comment by jrvansuita** [comment]
If you don't know what is or how to use Intents, you should study more about it. Also you have other options like addDonateAction(OnClickListener).

**Comment by aaravchaudhary** [comment]
Okk..thanks...for your advice..
