### ISSUE TITLE
Unable to include the library in a project

### ISSUE THREAD

**Issue by Christophe668** [jrvansuita/MaterialAbout#5]
Hi, 

I'm currently trying to include this library inside a project of mine but gradle seems unable to find the dependency. Jitpack.io is included in the repository as asked in the readme of the project.
I tried with **com.github.jrvansuita:MaterialAbout:0.0.5** (last version on Jitpack) and **MaterialAbout:+**

Regards

**Comment by Christophe668** [comment]
Update : 

It works if we use : 
com.github.jrvansuita:MaterialAbout:**v**0.0.5
and not : 
com.github.jrvansuita:MaterialAbout:0.0.5

I might be wrong but maybe that's why com.github.jrvansuita:MaterialAbout:+ wasn't working.

Also the documentation could use a small update :) 
AboutBuilder.with(...) doesn't exist (probably on an older version), AboutMe.with(...) on the other side does.

Thx !

**Comment by jrvansuita** [comment]
You are completely right. I fixed it.
