### ISSUE TITLE
Set HTML argument as string value

### ISSUE THREAD

**Issue by anileger** [jrvansuita/MaterialAbout#53]
**setBrief** method only accepts _String_ or _int_ value. But I want to customize all words in my text. (bold,italic etc.)

please add someting like that "**setBrief(Html.fromHtml(getString(R.string.html_styled_text)))**"

or 

give us a way to use setBrief method **more than one**. (If I use setBrief method more than one, only last method's parameter works.)

**Comment by jrvansuita** [comment]
Yeah, give me a pull request on `setBrief(Html.fromHtml(getString(R.string.html_styled_text)))` feature and we contribute together for this lib.

**Comment by gsantner** [comment]
This should all be possible with very minor modification. The parameter types just have to be swapped from `String` to `CharSequence` than you can put in Editeable, String, StringBuffer, Spanned,,.... and get this all for free without duplicated code

**Comment by jrvansuita** [comment]
@gsantner Can you give us a pull request?

**Comment by gsantner** [comment]
I'm not using this library yet on any project and don't know much about all available methods/places to edit. It should really be as easy as changing the `String title/text` to `CharSequence title/text`, from looking at README. I would need some time to get started.

BTW, As far as I understood the person-info is always on top right? Can this also be swapped somehow so person info is on bottom, and project-info/versionName is on top?

**Comment by tygalive** [comment]
Resolved in commit #93

**Comment by tygalive** [comment]
Am closing this after #93. please reopen if still not resolved
