### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by kareemElsayedDEV** [jrvansuita/MaterialAbout#55]
google play store account is directing to https://play.google.com/store/apps/dev?id= 
instead of https://play.google.com/store/apps/developer?id=

**Comment by jrvansuita** [comment]
What is you dev id?

Mine is 8002078663318221363. So [click here](https://play.google.com/store/apps/dev?id=8002078663318221363) you  will be redirect to my dev page. Replace with your Id on this link and you will be redirect to your dev page. No one haven't have issues on it.
