### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by JavaCafe01** [jrvansuita/MaterialAbout#58]
Even after I use the `.setAppIcon(R.mipmap.ic_launcher)` method the app icon does not show up. On some phones it does, for example, the Samsung Galaxy S8. But on my phone and the Pixel 2 emulator it does not show up.

**Comment by jrvansuita** [comment]
What happens when you download and play the publish app on: https://play.google.com/store/apps/details?id=com.vansuita.materialabout.sample
?

**Comment by JavaCafe01** [comment]
Your demo app is alright, but I think I figured it out. The app icon method would show any image from my drawable, but it would not show the launcher icon from mipmap.

**Comment by jrvansuita** [comment]
Nope
