### ISSUE TITLE
rtl text still on left side

### ISSUE THREAD

**Issue by AmineMessabhia** [jrvansuita/MaterialAbout#60]
Hello dude, congrats on this great library,

One little problem though, in the item xml, i suggest you use "Start" instead of "Left", this way on rtl mode, the strings would follow the icons.

I hope i could explain myself well.

Thanks again ^^

**Comment by jrvansuita** [comment]
Yes, sure it will be a great contribution by you to this library. We are here, open to receive any pull requests.

Thanks!

**Comment by tygalive** [comment]
Resolved in pull request #93

**Comment by tygalive** [comment]
Am closing this after #93. please reopen if still not resolved
