### ISSUE TITLE
addTwitterLink() not working as expected.

### ISSUE THREAD

**Issue by ItsCalebJones** [jrvansuita/MaterialAbout#63]
Hey there - i'm having an issue using the twitter link in my profile. When clicking on the link in the about I see a toast message "Cannot get users at this time. Please try again later"

`AboutBuilder builder = AboutBuilder.with(this).addTwitterLink("SpaceLaunchNow").build();`

**Comment by JavaCafe01** [comment]
Did you try putting "@" in front of the username? Just a suggestion...

**Comment by ItsCalebJones** [comment]
I just tried it - that does not work either.

**Comment by ItsCalebJones** [comment]
Check #64 for a potential solution.
