### ISSUE TITLE
Build For Support Lib 27

### ISSUE THREAD

**Issue by Patchett** [jrvansuita/MaterialAbout#65]
Hello,
Would it be possible to build the library for the latest support lib 27? Currently I am getting some warnings about mixing versions of dependencies (specifically cardview26) when I import this. Not breaking anything now, but would be nice to have an updated build for the latest support lib :)

**Comment by jrvansuita** [comment]
Yea @Patchett, can you do it for those who is using the lib? It's easy, clone the project, update the version and create a pull request.

:D
