### ISSUE TITLE
AndroidX Support?

### ISSUE THREAD

**Issue by KRIPT4** [jrvansuita/MaterialAbout#83]
Google has stopped supporting the support library and will only be releasing updates to AndroidX. These are mostly the same library, however the artifacts names and package names have all changed.

[Details from Google](https://developer.android.com/jetpack/androidx).

Future update for Android?

**Comment by codejunk1e** [comment]
This is really important now.

**Comment by Tiarait** [comment]
@jrvansuita 

If your project is already migrated to AndroidX, you should use AndroidX libraries exclusively. This means updating your dependencies and replacing any support library references in your code with their corresponding AndroidX equivalents.

But u use support library inside
[com.github.jrvansuita:IconHandler](https://github.com/jrvansuita/IconHandler)
