### ISSUE TITLE
Problem with the main icon

### ISSUE THREAD

**Issue by Asdamp** [jrvansuita/MaterialAbout#9]
First of all, awesome library!
I have a problem setting the main icon in the About. 
![device-2017-02-18-112843](https://cloud.githubusercontent.com/assets/3049958/23092518/787041ca-f5cd-11e6-8ca9-72f0da91803b.png)

As you can see the image is not correctly cropped

**Comment by jrvansuita** [comment]
Tried to reproduce here, but couldn't. Can you give your icon to teste here? Wich android version are you using? Can you tried it using the sample app with your icon? Try changing the `android:scaleType` attribute on `com.vansuita.materialabout.views.CircleImageView` at about.xml and teste it. Maybe using fitXY will help you. If it did the fix, get back to me with a pull request.

**Comment by jrvansuita** [comment]
Hey, also try to use a bigger image. And thanks, It's always gratifying see you using the library.
