### ISSUE TITLE
Implement New Google In-app review functionality. 

### ISSUE THREAD

**Issue by ismailnurudeen** [jrvansuita/MaterialAbout#90]
Instead of taking the user to PlayStore for Rating, use the new Google In-app review to display a rating page without exiting the app.

**Comment by tygalive** [comment]
This is a good idea though one drawback is the dialog is not guaranteed to show as outlined here

https://developer.android.com/guide/playcore/in-app-review#quotas

and sometimes giving the user a broken experience.

> The API does not indicate whether the user reviewed or not, or even whether the review dialog was shown.

https://developer.android.com/guide/playcore/in-app-review/kotlin-java#launch-review-flow

It might actually be preferable to set this using custom actions.
