### ISSUE TITLE
Nullpointers in the latest version

### ISSUE THREAD

**Issue by marbat87** [jrvansuita/MaterialAbout#94]
Hi, the new version leads to Nullpointers when some attributes are not filled.
These new "toStrings" additions are the cause.

Could you fix it please?
Thanks in advance
![image](https://user-images.githubusercontent.com/8694304/116850073-3d11a780-abf0-11eb-9966-103233a009f6.png)

**Comment by tygalive** [comment]
Ok, will look into it
